import 'package:fmbp_models/fmbp_models.dart';

class DefaultRecipesSeed {
  static final List<Recipe> seedRecipes = [
    // ==========================================
    // 🇻🇳 MÓN VIỆT NAM (VIETNAMESE)
    // ==========================================
    Recipe(
      id: 'seed_vn_bf_1',
      title: 'Bánh mì ốp la xúc xích pate',
      mealType: 'BREAKFAST',
      cuisine: 'VIETNAMESE',
      complexity: 'FAST_15',
      dietaryTags: ['QUICK', 'POPULAR'],
      estimatedCost: 2.2,
      currency: 'EUR',
      servings: 4,
      prepTime: 5,
      cookTime: 10,
      instructions: [
        'Làm nóng chảo với chút bơ hoặc dầu ăn, cho trứng vào chiên ốp la lòng đào hoặc chín tùy thích.',
        'Chiên sơ xúc xích cho vàng giòn 2 mặt.',
        'Nướng giòn bánh mì bằng nồi chiên không dầu hoặc lò nướng (3 phút ở 180°C).',
        'Quết pate, thêm dưa leo, ngò rí, tiêu, tương ớt và ăn kèm trứng xúc xích nóng giòn.',
      ],
      ingredients: [
        {'name': 'Trứng gà', 'quantity': 4, 'unit': 'quả', 'aisle': 'Trứng & Sữa'},
        {'name': 'Bánh mì baguette', 'quantity': 4, 'unit': 'ổ', 'aisle': 'Bánh mì'},
        {'name': 'Xúc xích', 'quantity': 4, 'unit': 'cây', 'aisle': 'Thịt nguội'},
        {'name': 'Pate gan', 'quantity': 100, 'unit': 'g', 'aisle': 'Thịt nguội'},
        {'name': 'Dưa leo & Ngò rí', 'quantity': 1, 'unit': 'phần', 'aisle': 'Rau củ quả'},
      ],
      localTip: 'Mua bánh mì baguette dạng nướng sơ (bake-at-home) tại siêu thị để luôn có bánh nóng giòn.',
      usageCount: 15,
      creatorId: 'SYSTEM_SEED',
    ),
    Recipe(
      id: 'seed_vn_bf_2',
      title: 'Cháo thịt bằm trứng bắc thảo nấm rơm',
      mealType: 'BREAKFAST',
      cuisine: 'VIETNAMESE',
      complexity: 'FAST_30',
      dietaryTags: ['WARM', 'COMFORT'],
      estimatedCost: 3.0,
      currency: 'EUR',
      servings: 4,
      prepTime: 10,
      cookTime: 20,
      instructions: [
        'Gạo vo sạch, rang sơ trên chảo cho thơm rồi cho vào nồi ninh cùng nước dùng hoặc nước sôi.',
        'Thịt bằm ướp hạt nêm, hành tím, tiêu. Phi thơm hành tím rồi xào săn thịt bằm và nấm rơm.',
        'Khi cháo nhừ, cho thịt xào và nấm vào khuấy đều, nêm nếm gia vị vừa ăn.',
        'Múc cháo ra tô, thêm trứng bắc thảo cắt múi cau, hành lá, gừng thái sợi và tiêu xay.',
      ],
      ingredients: [
        {'name': 'Gạo tẻ', 'quantity': 150, 'unit': 'g', 'aisle': 'Gạo & Ngũ cốc'},
        {'name': 'Thịt heo bằm', 'quantity': 250, 'unit': 'g', 'aisle': 'Thịt & Hải sản'},
        {'name': 'Trứng bắc thảo', 'quantity': 2, 'unit': 'quả', 'aisle': 'Trứng & Đồ khô'},
        {'name': 'Nấm rơm hoặc nấm mỡ', 'quantity': 100, 'unit': 'g', 'aisle': 'Rau củ quả'},
        {'name': 'Hành lá, gừng, tiêu', 'quantity': 1, 'unit': 'phần', 'aisle': 'Rau củ quả'},
      ],
      localTip: 'Dùng nồi áp suất hoặc cơm nguội xay nhuyễn để nấu cháo siêu nhanh chỉ trong 12 phút.',
      usageCount: 10,
      creatorId: 'SYSTEM_SEED',
    ),
    Recipe(
      id: 'seed_vn_lu_1',
      title: 'Thịt kho tàu trứng cút nước dừa',
      mealType: 'LUNCH',
      cuisine: 'VIETNAMESE',
      complexity: 'BALANCED',
      dietaryTags: ['FAMILY', 'TRADITIONAL'],
      estimatedCost: 6.5,
      currency: 'EUR',
      servings: 4,
      prepTime: 15,
      cookTime: 40,
      instructions: [
        'Thịt ba chỉ rửa sạch, cắt miếng vuông vừa ăn, chần qua nước sôi rồi ướp hành tỏi băm, nước mắm, đường, tiêu 20 phút.',
        'Thắng nước màu cánh gián từ đường rồi cho thịt vào xào săn cho thấm gia vị.',
        'Đổ nước dừa tươi vào ngập thịt, đun sôi rồi hạ nhỏ lửa hớt bọt kho liu riu.',
        'Cho trứng cút (hoặc trứng gà luộc) vào kho cùng đến khi thịt mềm rục, nước kho sánh vàng óng.',
      ],
      ingredients: [
        {'name': 'Thịt ba chỉ heo', 'quantity': 500, 'unit': 'g', 'aisle': 'Thịt & Hải sản'},
        {'name': 'Trứng cút hoặc trứng gà', 'quantity': 8, 'unit': 'quả', 'aisle': 'Trứng & Sữa'},
        {'name': 'Nước dừa tươi', 'quantity': 330, 'unit': 'ml', 'aisle': 'Đồ uống / Đồ hộp'},
        {'name': 'Hành tím, tỏi, ớt', 'quantity': 50, 'unit': 'g', 'aisle': 'Gia vị'},
        {'name': 'Gia vị (Nước mắm, đường, tiêu)', 'quantity': 1, 'unit': 'phần', 'aisle': 'Gia vị'},
      ],
      localTip: 'Nấu một nồi lớn ăn được cả 2 bữa trưa và tối, thịt kho càng hâm lại càng thấm đậm đà.',
      usageCount: 22,
      creatorId: 'SYSTEM_SEED',
    ),
    Recipe(
      id: 'seed_vn_lu_2',
      title: 'Sườn non rim mặn ngọt mặn mà đưa cơm',
      mealType: 'LUNCH',
      cuisine: 'VIETNAMESE',
      complexity: 'FAST_30',
      dietaryTags: ['POPULAR', 'KIDS_LOVE'],
      estimatedCost: 7.0,
      currency: 'EUR',
      servings: 4,
      prepTime: 10,
      cookTime: 25,
      instructions: [
        'Sườn non chặt khúc, chần nước sôi khử mùi hôi, ướp chút hạt nêm và tiêu.',
        'Pha sốt rim: 2 thìa nước mắm, 1.5 thìa đường, 1 thìa tương ớt, 1 thìa giấm/chanh, 2 thìa nước lọc.',
        'Phi thơm tỏi hành băm, cho sườn vào chiên xém vàng đều 2 mặt.',
        'Đổ bát nước sốt vào rim lửa nhỏ đến khi sốt keo lại bám đều quanh từng miếng sườn bóng bẩy.',
      ],
      ingredients: [
        {'name': 'Sườn non heo', 'quantity': 500, 'unit': 'g', 'aisle': 'Thịt & Hải sản'},
        {'name': 'Hành tỏi băm nhuyễn', 'quantity': 30, 'unit': 'g', 'aisle': 'Rau củ quả'},
        {'name': 'Gia vị (Nước mắm, giấm, đường, tương ớt)', 'quantity': 1, 'unit': 'phần', 'aisle': 'Gia vị'},
        {'name': 'Hành lá cắt khúc', 'quantity': 30, 'unit': 'g', 'aisle': 'Rau củ quả'},
      ],
      localTip: 'Thêm 1 chút tương ớt sẽ giúp màu sườn óng đỏ đẹp mắt và sốt sánh quyện hơn.',
      usageCount: 18,
      creatorId: 'SYSTEM_SEED',
    ),
    Recipe(
      id: 'seed_vn_dn_1',
      title: 'Canh chua cá hồi bạc hà đậu bắp',
      mealType: 'DINNER',
      cuisine: 'VIETNAMESE',
      complexity: 'FAST_30',
      dietaryTags: ['HEALTHY', 'OMEGA3', 'LIGHT'],
      estimatedCost: 6.8,
      currency: 'EUR',
      servings: 4,
      prepTime: 15,
      cookTime: 20,
      instructions: [
        'Đầu hoặc phi lê cá hồi rửa sạch với rượu gừng khử tanh, ướp chút nước mắm, tiêu, hành tím.',
        'Phi thơm tỏi, xào cà chua và thơm (dứa) cho ra màu đẹp, đổ nước vào đun sôi cùng nước cốt me.',
        'Nước sôi thả cá hồi vào nấu chín tới, vớt bọt kỹ để nước canh trong thanh.',
        'Cho bạc hà, đậu bắp, giá đỗ vào đun sôi bùng, nêm nước mắm ngò gai rau om rồi tắt bếp.',
      ],
      ingredients: [
        {'name': 'Cá hồi (lườn/đầu/phi lê)', 'quantity': 400, 'unit': 'g', 'aisle': 'Thịt & Hải sản'},
        {'name': 'Cà chua & Thơm (Dứa)', 'quantity': 250, 'unit': 'g', 'aisle': 'Rau củ quả'},
        {'name': 'Bạc hà (dọc mùng), đậu bắp, giá', 'quantity': 200, 'unit': 'g', 'aisle': 'Rau củ quả'},
        {'name': 'Cốt me & Rau ngò gai ngò om', 'quantity': 50, 'unit': 'g', 'aisle': 'Gia vị'},
      ],
      localTip: 'Ở nước ngoài có thể dùng gói gia vị Tom Yum hoặc sốt me chua Thái Lan có bán ở mọi siêu thị Á.',
      usageCount: 25,
      creatorId: 'SYSTEM_SEED',
    ),
    Recipe(
      id: 'seed_vn_dn_2',
      title: 'Bò xào bông cải xanh cần tây tỏi giòn',
      mealType: 'DINNER',
      cuisine: 'VIETNAMESE',
      complexity: 'FAST_15',
      dietaryTags: ['HIGH_PROTEIN', 'HEALTHY', 'QUICK'],
      estimatedCost: 7.5,
      currency: 'EUR',
      servings: 4,
      prepTime: 10,
      cookTime: 10,
      instructions: [
        'Thịt bò thái mỏng ngang thớ, ướp tỏi băm, dầu hào, tiêu, 1 thìa dầu ăn cho mềm.',
        'Bông cải xanh cắt miếng vừa ăn, chần qua nước sôi 1 phút rồi vớt ngâm nước đá cho giòn xanh.',
        'Phi thơm tỏi với lửa lớn, cho thịt bò vào đảo nhanh tay 1-2 phút vừa chín tái thì trút ra đĩa.',
        'Cho bông cải và cần tây vào xào chín tới, trút thịt bò vào đảo đều 30 giây rồi tắt bếp rắc tiêu.',
      ],
      ingredients: [
        {'name': 'Thịt bò phi lê', 'quantity': 350, 'unit': 'g', 'aisle': 'Thịt & Hải sản'},
        {'name': 'Bông cải xanh (Broccoli)', 'quantity': 1, 'unit': 'cây', 'aisle': 'Rau củ quả'},
        {'name': 'Cần tây & Tỏi', 'quantity': 100, 'unit': 'g', 'aisle': 'Rau củ quả'},
        {'name': 'Dầu hào & Gia vị', 'quantity': 1, 'unit': 'phần', 'aisle': 'Gia vị'},
      ],
      localTip: 'Xào lửa thật lớn và không xào bò quá lâu để giữ trọn vị ngọt mềm mọng nước.',
      usageCount: 19,
      creatorId: 'SYSTEM_SEED',
    ),

    // ==========================================
    // 🇫🇮 MÓN BẮC ÂU & PHẦN LAN (FINNISH / NORDIC)
    // ==========================================
    Recipe(
      id: 'seed_fi_bf_1',
      title: 'Kaurapuuro marjoilla (Cháo yến mạch việt quất hạt chia)',
      mealType: 'BREAKFAST',
      cuisine: 'FINNISH',
      complexity: 'FAST_15',
      dietaryTags: ['VEGAN', 'HEALTHY', 'FIBER'],
      estimatedCost: 1.8,
      currency: 'EUR',
      servings: 4,
      prepTime: 5,
      cookTime: 10,
      instructions: [
        'Cho yến mạch nguyên hạt và nước/sữa tươi vào nồi theo tỉ lệ 1:2 cùng 1 nhúm muối.',
        'Đun sôi nhẹ lửa vừa trong 6-8 phút, khuấy đều tay đến khi sánh mịn thơm lừng.',
        'Tắt bếp, cho 1 thìa bơ thực vật hoặc bơ lạt vào khuấy tan tạo độ béo ngậy.',
        'Múc ra bát, phủ quả việt quất/dâu tây tươi, rắc hạt chia và rưới chút mật ong.',
      ],
      ingredients: [
        {'name': 'Yến mạch Phần Lan (Kaurahiutale)', 'quantity': 200, 'unit': 'g', 'aisle': 'Ngũ cốc'},
        {'name': 'Sữa tươi hoặc sữa yến mạch', 'quantity': 500, 'unit': 'ml', 'aisle': 'Trứng & Sữa'},
        {'name': 'Quả mọng việt quất / phúc bồn tử', 'quantity': 150, 'unit': 'g', 'aisle': 'Rau củ quả'},
        {'name': 'Hạt chia & Mật ong', 'quantity': 1, 'unit': 'phần', 'aisle': 'Đồ khô & Gia vị'},
      ],
      localTip: 'Quả mọng đông lạnh (Pakastemarjat) tại Phần Lan có giá rất rẻ và dồi dào chất chống oxy hóa.',
      usageCount: 14,
      creatorId: 'SYSTEM_SEED',
    ),
    Recipe(
      id: 'seed_fi_lu_1',
      title: 'Lohikeitto (Súp kem cá hồi khoai tây Phần Lan truyền thống)',
      mealType: 'LUNCH',
      cuisine: 'FINNISH',
      complexity: 'FAST_30',
      dietaryTags: ['NORDIC_ICONIC', 'OMEGA3', 'WARM'],
      estimatedCost: 7.8,
      currency: 'EUR',
      servings: 4,
      prepTime: 10,
      cookTime: 20,
      instructions: [
        'Khoai tây, cà rốt gọt vỏ cắt khối vuông; tỏi tây (leek) thái khoanh tròn.',
        'Đun sôi nước dùng cá hoặc nước cùng bơ, lá nguyệt quế và hạt tiêu sọ, cho khoai tây cà rốt vào nấu 10 phút đến khi mềm.',
        'Cắt cá hồi tươi thành miếng vuông dày 2cm, thả vào nồi súp đun nhẹ 3-4 phút cho cá vừa chín mềm béo ngậy.',
        'Đổ kem tươi (Ruokakerma) vào khuấy nhẹ, nêm muối tiêu vừa ăn, tắt bếp và rắc thật nhiều thì là tươi (Tilli).',
      ],
      ingredients: [
        {'name': 'Phi lê cá hồi tươi (Lohi)', 'quantity': 450, 'unit': 'g', 'aisle': 'Thịt & Hải sản'},
        {'name': 'Khoai tây & Cà rốt', 'quantity': 400, 'unit': 'g', 'aisle': 'Rau củ quả'},
        {'name': 'Tỏi tây (Purjo) & Bơ', 'quantity': 150, 'unit': 'g', 'aisle': 'Rau củ quả'},
        {'name': 'Kem nấu ăn (Ruokakerma 15%)', 'quantity': 200, 'unit': 'ml', 'aisle': 'Trứng & Sữa'},
        {'name': 'Thì là tươi Phần Lan (Tilli)', 'quantity': 1, 'unit': 'bó', 'aisle': 'Rau củ quả'},
      ],
      localTip: 'Món súp quốc dân Phần Lan, ăn kèm với bánh mì lúa mạch đen (Ruisleipä) quết bơ cực kỳ hợp.',
      usageCount: 30,
      creatorId: 'SYSTEM_SEED',
    ),
    Recipe(
      id: 'seed_fi_dn_1',
      title: 'Lihapullat ja muusi (Thịt viên sốt kem khoai tây nghiền)',
      mealType: 'DINNER',
      cuisine: 'FINNISH',
      complexity: 'BALANCED',
      dietaryTags: ['COMFORT', 'FAMILY_FAV'],
      estimatedCost: 6.2,
      currency: 'EUR',
      servings: 4,
      prepTime: 15,
      cookTime: 30,
      instructions: [
        'Trộn thịt bò heo xay với vụn bánh mì ngâm sữa, trứng gà, hành tây xào băm nhỏ, muối tiêu; vo tròn từng viên.',
        'Chiên vàng các viên thịt trên chảo bơ nóng cho xém giòn các mặt.',
        'Nấu sốt kem nâu (ruskeakastike): dùng bơ và bột mì trên chảo thịt, thêm nước dùng bò và kem tươi nấu sánh mịn.',
        'Khoai tây luộc chín mềm, nghiền nhuyễn với bơ lạt và sữa ấm. Ăn kèm thịt viên sốt kem và mứt dâu lingonberry.',
      ],
      ingredients: [
        {'name': 'Thịt xay hỗn hợp bò heo (Jauheliha)', 'quantity': 500, 'unit': 'g', 'aisle': 'Thịt & Hải sản'},
        {'name': 'Khoai tây (Peruna)', 'quantity': 600, 'unit': 'g', 'aisle': 'Rau củ quả'},
        {'name': 'Kem tươi (Kuohukerma)', 'quantity': 150, 'unit': 'ml', 'aisle': 'Trứng & Sữa'},
        {'name': 'Bơ lạt (Voi)', 'quantity': 60, 'unit': 'g', 'aisle': 'Trứng & Sữa'},
        {'name': 'Mứt dâu rừng Lingonberry (Puukkahillo)', 'quantity': 100, 'unit': 'g', 'aisle': 'Đồ hộp & Mứt'},
      ],
      localTip: 'Loại khoai tây vỏ đỏ (punainen peruna) là loại chuyên dụng để làm món khoai tây nghiền dẻo mịn nhất.',
      usageCount: 20,
      creatorId: 'SYSTEM_SEED',
    ),

    // ==========================================
    // 🇪🇺 MÓN CHÂU ÂU & Ý (EUROPEAN / ITALIAN)
    // ==========================================
    Recipe(
      id: 'seed_eu_bf_1',
      title: 'French Toast bánh mì nướng bơ mật ong chuối caramel',
      mealType: 'BREAKFAST',
      cuisine: 'EUROPEAN',
      complexity: 'FAST_15',
      dietaryTags: ['SWEET', 'QUICK'],
      estimatedCost: 2.5,
      currency: 'EUR',
      servings: 4,
      prepTime: 5,
      cookTime: 10,
      instructions: [
        'Đánh tan 2 quả trứng gà cùng 80ml sữa tươi, chút bột quế và vani.',
        'Nhúng từng lát bánh mì sandwich vào hỗn hợp trứng sữa khoảng 10 giây mỗi mặt.',
        'Đun chảy bơ trên chảo, áp chảo bánh mì đến khi vàng ruộm 2 mặt thơm lừng.',
        'Xếp bánh ra đĩa cùng chuối cắt lát, rưới siro phong hoặc mật ong và thưởng thức.',
      ],
      ingredients: [
        {'name': 'Bánh mì sandwich lát dày', 'quantity': 6, 'unit': 'lát', 'aisle': 'Bánh mì'},
        {'name': 'Trứng gà & Sữa tươi', 'quantity': 2, 'unit': 'quả', 'aisle': 'Trứng & Sữa'},
        {'name': 'Chuối chín', 'quantity': 2, 'unit': 'quả', 'aisle': 'Rau củ quả'},
        {'name': 'Bơ lạt, bột quế, mật ong', 'quantity': 1, 'unit': 'phần', 'aisle': 'Gia vị'},
      ],
      localTip: 'Tận dụng bánh mì sandwich cũ hơi khô sẽ hút trứng sữa ngon hơn và không bị nhũn.',
      usageCount: 16,
      creatorId: 'SYSTEM_SEED',
    ),
    Recipe(
      id: 'seed_eu_lu_1',
      title: 'Spaghetti Carbonara kem trứng ba chỉ xông khói chuẩn vị Ý',
      mealType: 'LUNCH',
      cuisine: 'EUROPEAN',
      complexity: 'FAST_20',
      dietaryTags: ['ITALIAN_CLASSIC', 'FAST'],
      estimatedCost: 5.5,
      currency: 'EUR',
      servings: 4,
      prepTime: 5,
      cookTime: 15,
      instructions: [
        'Luộc mì Spaghetti trong nước sôi có muối khoảng 8-9 phút cho chín vừa tới (Al dente), giữ lại 1 bát nước luộc mì.',
        'Thịt ba chỉ xông khói (Pancetta/Bacon) cắt sợi nhỏ, áp chảo lửa vừa cho ra bớt mỡ và giòn thơm.',
        'Đánh tan 3 lòng đỏ trứng + 1 quả trứng nguyên với phô mai Parmesan bào mịn và thật nhiều tiêu đen.',
        'Trộn mì nóng vào chảo thịt, tắt bếp rồi nhanh tay đổ hỗn hợp trứng phô mai vào đảo đều tạo lớp sốt kem béo mịn quyến rũ.',
      ],
      ingredients: [
        {'name': 'Mì Spaghetti', 'quantity': 350, 'unit': 'g', 'aisle': 'Mì & Pasta'},
        {'name': 'Thịt ba chỉ xông khói (Bacon)', 'quantity': 200, 'unit': 'g', 'aisle': 'Thịt nguội'},
        {'name': 'Trứng gà tươi', 'quantity': 4, 'unit': 'quả', 'aisle': 'Trứng & Sữa'},
        {'name': 'Phô mai Parmesan bào', 'quantity': 80, 'unit': 'g', 'aisle': 'Trứng & Sữa'},
        {'name': 'Tiêu đen xay', 'quantity': 1, 'unit': 'thìa', 'aisle': 'Gia vị'},
      ],
      localTip: 'Tuyệt đối tắt bếp trước khi trộn trứng để sốt không bị vón cục thành trứng bác.',
      usageCount: 28,
      creatorId: 'SYSTEM_SEED',
    ),
    Recipe(
      id: 'seed_eu_dn_1',
      title: 'Beef Steak sốt tiêu đen khoai tây chiên măng tây',
      mealType: 'DINNER',
      cuisine: 'EUROPEAN',
      complexity: 'FAST_30',
      dietaryTags: ['HIGH_PROTEIN', 'PREMIUM'],
      estimatedCost: 9.5,
      currency: 'EUR',
      servings: 4,
      prepTime: 10,
      cookTime: 15,
      instructions: [
        'Thịt bò bít tết (thăn lưng/ribeye) thấm khô ráo, rắc muối biển và tiêu đen giã dập đều 2 mặt.',
        'Đun nóng chảo gang với dầu ăn bốc khói nhẹ, áp chảo thịt 2.5 phút mỗi mặt cho xém vàng đẹp mắt.',
        'Thêm bơ lạt, nhánh hương thảo (rosemary) và tỏi đập dập, múc bơ nóng rưới liên tục lên miếng thịt trong 1 phút rồi gắp ra nghỉ 5 phút.',
        'Xào măng tây trên chảo thơm bơ, làm sốt tiêu đen kem tươi rưới lên đĩa bít tết mọng nước.',
      ],
      ingredients: [
        {'name': 'Thịt bò thăn bít tết (Steak)', 'quantity': 500, 'unit': 'g', 'aisle': 'Thịt & Hải sản'},
        {'name': 'Măng tây tươi (Asparagus)', 'quantity': 250, 'unit': 'g', 'aisle': 'Rau củ quả'},
        {'name': 'Bơ lạt & Hương thảo (Rosemary)', 'quantity': 50, 'unit': 'g', 'aisle': 'Trứng & Sữa'},
        {'name': 'Tiêu đen & Kem nấu ăn', 'quantity': 100, 'unit': 'ml', 'aisle': 'Gia vị'},
      ],
      localTip: 'Để thịt bò nghỉ (resting) đủ 5 phút trước khi cắt giúp nước ngọt phân bổ đều mà không bị chảy ra đĩa.',
      usageCount: 21,
      creatorId: 'SYSTEM_SEED',
    ),

    // ==========================================
    // 🇯🇵🇰🇷 MÓN CHÂU Á (JAPANESE / KOREAN)
    // ==========================================
    Recipe(
      id: 'seed_as_bf_1',
      title: 'Cơm nắm Onigiri cá ngừ sốt mayo rong biển',
      mealType: 'BREAKFAST',
      cuisine: 'ASIAN',
      complexity: 'FAST_15',
      dietaryTags: ['CONVENIENT', 'KIDS_FAV'],
      estimatedCost: 2.0,
      currency: 'EUR',
      servings: 4,
      prepTime: 10,
      cookTime: 5,
      instructions: [
        'Cá ngừ đóng hộp chắt ráo nước, trộn đều với 2 thìa sốt mayonnaise Kewpie, chút xì dầu và tiêu.',
        'Cơm dẻo nóng trộn nhẹ cùng chút dầu mè và muối biển hoặc gói gia vị rắc cơm Furikake.',
        'Lấy một phần cơm đặt vào lòng bàn tay, cho nhân cá ngừ vào giữa rồi nắm thành hình tam giác chắc tay.',
        'Bọc một miếng rong biển Nori giòn quanh đáy nắm cơm và thưởng thức.',
      ],
      ingredients: [
        {'name': 'Cá ngừ ngâm dầu hộp (Tuna)', 'quantity': 2, 'unit': 'hộp', 'aisle': 'Đồ hộp'},
        {'name': 'Gạo dẻo Nhật hoặc gạo thơm', 'quantity': 300, 'unit': 'g', 'aisle': 'Gạo & Ngũ cốc'},
        {'name': 'Sốt Mayonnaise Kewpie', 'quantity': 50, 'unit': 'g', 'aisle': 'Gia vị'},
        {'name': 'Lá rong biển Nori', 'quantity': 6, 'unit': 'lá', 'aisle': 'Đồ khô Á'},
      ],
      localTip: 'Thoa một chút nước muối loãng lên lòng bàn tay trước khi nắm cơm để cơm không dính vào tay.',
      usageCount: 17,
      creatorId: 'SYSTEM_SEED',
    ),
    Recipe(
      id: 'seed_as_lu_1',
      title: 'Cơm bò Gyudon Nhật Bản sốt hành tây ngọt thanh',
      mealType: 'LUNCH',
      cuisine: 'ASIAN',
      complexity: 'FAST_20',
      dietaryTags: ['JAPANESE', 'DELICIOUS'],
      estimatedCost: 6.5,
      currency: 'EUR',
      servings: 4,
      prepTime: 10,
      cookTime: 10,
      instructions: [
        'Hành tây bổ múi cau mỏng; gừng thái lát mỏng.',
        'Đun sôi hỗn hợp nước sốt gồm: 150ml nước dashi, 3 thìa xì dầu Nhật (Shoyu), 2 thìa rượu mirin, 1 thìa đường.',
        'Cho hành tây vào nấu 5 phút cho mềm và ngấm vị ngọt, sau đó trải từng lát thịt bò mỏng vào nấu vừa chín tới trong 2-3 phút.',
        'Múc cơm trắng ra bát tô, gắp thịt bò và hành tây phủ lên trên, chan nước sốt, thêm trứng lòng đào Onsen và gừng đỏ ngâm.',
      ],
      ingredients: [
        {'name': 'Thịt ba chỉ bò cuộn thái mỏng', 'quantity': 400, 'unit': 'g', 'aisle': 'Thịt & Hải sản'},
        {'name': 'Hành tây trắng', 'quantity': 2, 'unit': 'củ', 'aisle': 'Rau củ quả'},
        {'name': 'Xì dầu Nhật (Shoyu) & Mirin', 'quantity': 1, 'unit': 'phần', 'aisle': 'Gia vị'},
        {'name': 'Trứng gà (luộc lòng đào)', 'quantity': 4, 'unit': 'quả', 'aisle': 'Trứng & Sữa'},
      ],
      localTip: 'Dùng thịt bò ba chỉ cuộn đông lạnh bán sẵn giúp tiết kiệm thời gian cắt và nấu siêu mềm.',
      usageCount: 24,
      creatorId: 'SYSTEM_SEED',
    ),
    Recipe(
      id: 'seed_as_dn_1',
      title: 'Canh Kim Chi Hàn Quốc đậu hũ non thịt ba chỉ',
      mealType: 'DINNER',
      cuisine: 'ASIAN',
      complexity: 'FAST_30',
      dietaryTags: ['KOREAN', 'SPICY', 'COMFORT'],
      estimatedCost: 5.8,
      currency: 'EUR',
      servings: 4,
      prepTime: 10,
      cookTime: 20,
      instructions: [
        'Thịt ba chỉ cắt miếng vừa ăn, xào săn trên nồi với chút dầu mè và tỏi băm.',
        'Cho kim chi cải thảo cắt khúc vào xào chung 3 phút cho dậy mùi thơm chua cay.',
        'Đổ nước dùng (hoặc nước lọc) cùng 1 bát nước cốt kim chi vào đun sôi, nêm thêm 1 thìa ớt bột Hàn Quốc Gochugaru và xì dầu.',
        'Hạ lửa vừa thả đậu hũ non cắt miếng vuông và nấm kim châm vào nấu 5 phút, rắc hành boa-rô rồi tắt bếp.',
      ],
      ingredients: [
        {'name': 'Kim chi cải thảo Hàn Quốc', 'quantity': 300, 'unit': 'g', 'aisle': 'Đồ muối & Lên men'},
        {'name': 'Thịt ba chỉ heo', 'quantity': 250, 'unit': 'g', 'aisle': 'Thịt & Hải sản'},
        {'name': 'Đậu hũ non (Soft Tofu)', 'quantity': 1, 'unit': 'hộp', 'aisle': 'Đậu hũ & Đồ chay'},
        {'name': 'Nấm kim châm & Hành boa-rô', 'quantity': 150, 'unit': 'g', 'aisle': 'Rau củ quả'},
      ],
      localTip: 'Dùng kim chi đã chua nhiều (muối lâu ngày) sẽ nấu nước canh đậm đà và ngon hơn rất nhiều.',
      usageCount: 26,
      creatorId: 'SYSTEM_SEED',
    ),

    // ==========================================
    // 🥗 MÓN HEALTHY & EAT CLEAN & CHAY (HEALTHY / VEGAN)
    // ==========================================
    Recipe(
      id: 'seed_hl_bf_1',
      title: 'Smoothie Bowl bơ chuối sữa hạt rắc Granola giòn',
      mealType: 'BREAKFAST',
      cuisine: 'HEALTHY',
      complexity: 'FAST_15',
      dietaryTags: ['HEALTHY', 'VEGAN', 'CLEAN_EAT'],
      estimatedCost: 2.8,
      currency: 'EUR',
      servings: 4,
      prepTime: 10,
      cookTime: 0,
      instructions: [
        'Cho bơ chín, chuối đông lạnh, cải bó xôi (spinach) và 150ml sữa hạnh nhân/sữa yến mạch vào máy xay sinh tố.',
        'Xay nhuyễn ở tốc độ cao đến khi hỗn hợp sánh đặc mịn như kem.',
        'Đổ hỗn hợp ra bát sinh tố (bowl).',
        'Trang trí với dâu tây, hạt chia, dừa sấy giòn và ngũ cốc Granola.',
      ],
      ingredients: [
        {'name': 'Bơ tươi & Chuối đông lạnh', 'quantity': 300, 'unit': 'g', 'aisle': 'Rau củ quả'},
        {'name': 'Sữa hạt (Hạnh nhân/Yến mạch)', 'quantity': 200, 'unit': 'ml', 'aisle': 'Trứng & Sữa'},
        {'name': 'Ngũ cốc Granola & Hạt chia', 'quantity': 100, 'unit': 'g', 'aisle': 'Ngũ cốc'},
        {'name': 'Rau bina non (Baby Spinach)', 'quantity': 50, 'unit': 'g', 'aisle': 'Rau củ quả'},
      ],
      localTip: 'Chuối đông lạnh là bí quyết giúp bát sinh tố sánh đặc mát lạnh mà không cần thêm đá làm loãng vị.',
      usageCount: 13,
      creatorId: 'SYSTEM_SEED',
    ),
    Recipe(
      id: 'seed_hl_lu_1',
      title: 'Salad ức gà áp chảo sốt mè rang trứng luộc lòng đào',
      mealType: 'LUNCH',
      cuisine: 'HEALTHY',
      complexity: 'FAST_20',
      dietaryTags: ['HIGH_PROTEIN', 'LOW_CARB', 'FITNESS'],
      estimatedCost: 4.8,
      currency: 'EUR',
      servings: 4,
      prepTime: 10,
      cookTime: 10,
      instructions: [
        'Ức gà ướp muối tiêu, chút tỏi ớt bột và 1 thìa dầu olive 10 phút.',
        'Áp chảo ức gà mỗi mặt 5-6 phút ở lửa vừa cho chín vàng thơm mọng nước, để nguội bớt rồi thái lát.',
        'Rửa sạch các loại xà lách giòn, cà chua bi, dưa leo xếp vào tô lớn.',
        'Xếp ức gà và trứng luộc cắt đôi lên trên, rưới sốt mè rang Kewpie thơm bùi và thưởng thức.',
      ],
      ingredients: [
        {'name': 'Ức gà phi lê tươi', 'quantity': 450, 'unit': 'g', 'aisle': 'Thịt & Hải sản'},
        {'name': 'Xà lách hỗn hợp & Cà chua bi', 'quantity': 300, 'unit': 'g', 'aisle': 'Rau củ quả'},
        {'name': 'Trứng gà luộc', 'quantity': 4, 'unit': 'quả', 'aisle': 'Trứng & Sữa'},
        {'name': 'Sốt mè rang Kewpie Roasted Sesame', 'quantity': 80, 'unit': 'ml', 'aisle': 'Gia vị & Sốt'},
      ],
      localTip: 'Không áp chảo quá khô; đậy vung chảo ở 2 phút cuối sẽ giúp ức gà chín đều và siêu mềm ngọt.',
      usageCount: 27,
      creatorId: 'SYSTEM_SEED',
    ),
    Recipe(
      id: 'seed_hl_dn_1',
      title: 'Đậu hũ nướng sốt Teriyaki nấm đùi gà thanh đạm',
      mealType: 'DINNER',
      cuisine: 'HEALTHY',
      complexity: 'FAST_20',
      dietaryTags: ['VEGETARIAN', 'VEGAN', 'LIGHT_DINNER'],
      estimatedCost: 3.8,
      currency: 'EUR',
      servings: 4,
      prepTime: 10,
      cookTime: 10,
      instructions: [
        'Đậu hũ cứng thấm khô ráo, cắt khối vuông, áo nhẹ 1 lớp mỏng bột bắp.',
        'Áp chảo đậu hũ hoặc nướng nồi chiên không dầu (180°C trong 10 phút) cho vàng giòn các mặt.',
        'Nấm đùi gà thái lát dày, xào thơm trên chảo cùng tỏi băm.',
        'Cho đậu hũ vào chảo nấm, rưới 3 thìa sốt Teriyaki đun liu riu 2 phút cho sốt áo đều bóng bẩy, rắc mè trắng.',
      ],
      ingredients: [
        {'name': 'Đậu hũ cứng (Firm Tofu)', 'quantity': 400, 'unit': 'g', 'aisle': 'Đậu hũ & Đồ chay'},
        {'name': 'Nấm đùi gà tươi (King Oyster Mushroom)', 'quantity': 200, 'unit': 'g', 'aisle': 'Rau củ quả'},
        {'name': 'Sốt Teriyaki Nhật & Mè trắng', 'quantity': 60, 'unit': 'ml', 'aisle': 'Gia vị'},
        {'name': 'Hành lá tươi', 'quantity': 30, 'unit': 'g', 'aisle': 'Rau củ quả'},
      ],
      localTip: 'Món ăn chay thanh đạm, giàu đạm thực vật và dễ tiêu hóa, rất thích hợp cho bữa tối nhẹ bụng.',
      usageCount: 15,
      creatorId: 'SYSTEM_SEED',
    ),

    // ==========================================
    // 🇨🇳 MÓN TRUNG HOA (CHINESE)
    // ==========================================
    Recipe(
      id: 'seed_cn_bf_1',
      title: 'Há cảo tôm thịt hấp Dimsum Hong Kong',
      mealType: 'BREAKFAST',
      cuisine: 'CHINESE',
      complexity: 'FAST_15',
      dietaryTags: ['DIMSUM', 'POPULAR'],
      estimatedCost: 3.5,
      currency: 'EUR',
      servings: 4,
      prepTime: 5,
      cookTime: 10,
      instructions: [
        'Lót giấy nến hoặc lá bắp cải vào xửng hấp Dimsum.',
        'Xếp há cảo tôm thịt vào xửng, đậy nắp hấp lửa lớn trong 8-10 phút đến khi vỏ trong veo.',
        'Pha nước chấm: xì dầu, giấm tiều (giấm đỏ), gừng thái sợi và chút dầu ớt sa tế.',
        'Thưởng thức há cảo nóng hổi cùng trà hoa cúc hoặc trà Ô long.',
      ],
      ingredients: [
        {'name': 'Há cảo / Sủi cảo tôm thịt', 'quantity': 16, 'unit': 'viên', 'aisle': 'Đồ đông lạnh Á'},
        {'name': 'Xì dầu & Giấm tiều đỏ', 'quantity': 1, 'unit': 'phần', 'aisle': 'Gia vị'},
        {'name': 'Gừng tươi & Ớt sa tế', 'quantity': 30, 'unit': 'g', 'aisle': 'Gia vị'},
      ],
      localTip: 'Các gói há cảo Dimsum đông lạnh tại siêu thị Á có chất lượng rất ngon và hấp cực nhanh cho bữa sáng.',
      usageCount: 20,
      creatorId: 'SYSTEM_SEED',
    ),
    Recipe(
      id: 'seed_cn_dn_1',
      title: 'Gà Kung Pao Tứ Xuyên xào đậu phộng ớt khô',
      mealType: 'DINNER',
      cuisine: 'CHINESE',
      complexity: 'FAST_20',
      dietaryTags: ['SICHUAN', 'POPULAR', 'SPICY'],
      estimatedCost: 6.0,
      currency: 'EUR',
      servings: 4,
      prepTime: 10,
      cookTime: 10,
      instructions: [
        'Đùi gà rút xương cắt khối vuông 2cm, ướp xì dầu, rượu hoa tiêu Thiệu Hưng và bột bắp.',
        'Pha sốt Kung Pao: 2 thìa xì dầu đen, 1 thìa giấm đen Trấn Giang, 1 thìa đường, 1/2 thìa dầu mè, chút nước bột bắp.',
        'Phi thơm tỏi, gừng, đầu hành boa-rô và ớt khô Tứ Xuyên với dầu nóng cho dậy mùi thơm nồng.',
        'Cho thịt gà vào xào săn chín tới trên lửa lớn, đổ bát nước sốt và đậu phộng rang giòn vào đảo nhanh tay 30 giây rồi tắt bếp.',
      ],
      ingredients: [
        {'name': 'Thịt đùi gà rút xương', 'quantity': 450, 'unit': 'g', 'aisle': 'Thịt & Hải sản'},
        {'name': 'Đậu phộng (lạc) rang giòn', 'quantity': 80, 'unit': 'g', 'aisle': 'Đồ khô & Hạt'},
        {'name': 'Ớt khô & Tiêu Tứ Xuyên', 'quantity': 20, 'unit': 'g', 'aisle': 'Gia vị'},
        {'name': 'Hành boa-rô, gừng, tỏi', 'quantity': 60, 'unit': 'g', 'aisle': 'Rau củ quả'},
        {'name': 'Xì dầu & Giấm đen Trấn Giang', 'quantity': 1, 'unit': 'phần', 'aisle': 'Gia vị'},
      ],
      localTip: 'Món xào kinh điển của Tứ Xuyên với vị chua ngọt cay mặn hài hòa cực kỳ đưa cơm.',
      usageCount: 25,
      creatorId: 'SYSTEM_SEED',
    ),
  ];
}

